version: '3.2'

services:

  mount:
    image: eclipfs/mount
    volumes:
      - /mnt/eclipfs:/mnt:shared
      # - type: bind
      #   source: /mnt/eclipfs
      #   target: /mnt
      #   bind:
      #     propagation: shared
    cap_add: ['sys_admin']
    devices: ['/dev/fuse']
    security_opt: ['apparmor:unconfined']
    privileged: true
    environment:
      METASERVER: enter metaserver address
      USERNAME: enter username
      PASSWORD: enter password
      LOCATION: enter preferred location for transfers
