version: '3'

services:

  node_a:
    build: .
    ports: [8000:80]
    volumes: ['/opt/chunkserver1:/data']
    environment:
      TOKEN: uOSrCMZRKuvkiSHOPQmiBsLc0kzVftlL
      METASERVER_ADDRESS: http://10.0.0.124:7779
      OWN_ADDRESS: 'http://10.0.0.124:8000'
      RESERVATION: 50

  node_b:
    build: .
    ports: [8001:80]
    volumes: ['/opt/chunkserver2:/data']
    environment:
      TOKEN: RxSKMtCM95hdsLyq6W7KsWuqLkucA6mM
      METASERVER_ADDRESS: http://10.0.0.124:7779
      OWN_ADDRESS: 'http://10.0.0.124:8001'
