version: '3'

services:

  node_a:
    build: .
    ports: [8000:80]
    volumes: ['/opt/chunkserver1:/data']
    environment:
      TOKEN: WCraw4Dk7B1Dd6RbWM3wNf7YmliFIXqfj8cJzaFD0Y7rchhSzGAn75NtKf2PQM9ZmwyFXlQa29RdunPbuDw2akflQ2KIj7LR9cuA1PC5r0ak9QUzpVeWSWxzIy9gyysA
      METASERVER_ADDRESS: http://10.0.0.124:7779
      OWN_ADDRESS: 'http://10.0.0.124:8000'
      RESERVATION: 50

  node_b:
    build: .
    ports: [8001:80]
    volumes: ['/opt/chunkserver2:/data']
    environment:
      TOKEN: gLu0H5IM1EGFZwqpgfn7C2gqM7nygFQaF5v2Ith3xxGxI4i1cD7fHFqlPNqV7n2CRTmPSuGToeHhk8CIcl8xRwsUVwkJOGzsXIU9yOMV134Os8qbzX5DfANiaD1PXZXt
      METASERVER_ADDRESS: http://10.0.0.124:7779
      OWN_ADDRESS: 'http://10.0.0.124:8001'
