version: '3'

services:

  node_a:
    build: .
    ports: [7780:80]
    volumes: ['/opt/chunkserver1:/data']
    environment:
      TOKEN: tscP8cd0EAkl2tnj0dIkX9XvCwmes01K
      METASERVER_ADDRESS: http://10.0.0.166:7779
      OWN_ADDRESS: 'http://10.0.0.166:7780'
      RESERVATION: 50

  node_b:
    build: .
    ports: [7781:80]
    volumes: ['/opt/chunkserver2:/data']
    environment:
      TOKEN: 204lI9u9Gr99hLDEchrHMbzAscCQRtZn
      METASERVER_ADDRESS: http://10.0.0.166:7779
      OWN_ADDRESS: 'http://10.0.0.166:7781'
      DEBUG: 1
