version: '3'

services:

  node_a:
    image: eclipfs/chunkserver
    ports: [8000:80]
    volumes: ['/opt/chunkserver1:/data']
    environment:
      TOKEN: enter token here
      METASERVER_ADDRESS: enter address here
      OWN_ADDRESS: enter address here

  node_b:
    build: eclipfs/chunkserver
    ports: [8001:80]
    volumes: ['/opt/chunkserver2:/data']
    environment:
      TOKEN: enter token here
      METASERVER_ADDRESS: enter address here
      OWN_ADDRESS: enter address here
