version: '3'

services:

  node_a:
    build: .
    ports: [8000:80]
    volumes: ['/opt/chunkserver1:/data']
    environment:
      TOKEN: IPysRFtPZwtODawmXTSKSHKxxwzBOvKBmIDf5WBdglPBwgq6gLUU5QfHyNQIKpFnt7PSrS0jzyLe4HcHeLQXtWJWKum85PDR5y79pWrPIJVmcR8QE9IJwunP2oxhGNld
      METASERVER_ADDRESS: http://10.0.0.124:7779
      OWN_ADDRESS: 'http://10.0.0.124:8000'

  node_b:
    build: .
    ports: [8001:80]
    volumes: ['/opt/chunkserver2:/data']
    environment:
      TOKEN: 6mwEEQLUmqThs8W9MnWR9Acrmf9JMnGkdeSHHVX5ieKx7QXsOdJsBr6PoX0hbScDGc4rSTmuksJ8V0gU2KfDIoAzw5g9FueaXLpANYCDknI0tg4AUGKtTtuBm5aSj7R9
      METASERVER_ADDRESS: http://10.0.0.124:7779
      OWN_ADDRESS: 'http://10.0.0.124:8001'
